// Single source for the v4 decks, their speaker notes and scripts-m4-m5-v4.md.
// say = word-for-word script. Lines in [brackets] are actions, not spoken.
// demo = extra minutes of live TradingView time on a screen-share slide.

const DISCLAIMER = {
  kind: "disclaimer",
  title: "Before We Start",
  lines: [
    "This is education, not financial advice.",
    "Futures trading carries a real risk of loss. You can lose more than you planned if you trade without a stop.",
    "Chart examples are for teaching. Past results don't predict future results.",
    "Only trade money you can afford to lose.",
  ],
};

const M4 = {
  file: "module_4_liquidity_volume_v4.pptx",
  module: "MODULE 4",
  name: "Session Liquidity & Volume Profile",
  lessons: {
    "4.1": "What Session Liquidity Means",
    "4.2": "Reading the Three Sessions",
    "4.3": "Fixed Range Volume Profile Basics",
    "4.4": "Using Volume to Confirm Zones",
    "4.5": "Using the POC as an Entry or Exit",
    "4.6": "Combining Both Tools with CRT",
  },
  slides: [
    { kind: "title", lesson: "intro", module: "MODULE 4", title: "Session Liquidity &\nVolume Profile", sub: "Where liquidity sits, and whether volume agrees",
      say: "Welcome to Module 4. In Module 3 you learned the CRT setup. Now we answer two questions that make that setup better. Where is price headed? And does volume agree with the move? That's session liquidity and volume profile." },
    { ...DISCLAIMER, lesson: "intro",
      say: "Quick note before we start. This is education, not financial advice. Futures can take money out of your account fast, and more than you planned if you trade without a stop. The chart examples are for teaching. Nothing I show you is a promise of what the next trade does. Only trade money you can afford to lose." },
    { kind: "agenda", lesson: "intro", title: "Module 4 Lessons",
      say: "Here's the plan. Six short lessons. 4.1 and 4.2 are session liquidity: where the orders sit. 4.3 and 4.4 are volume profile: where the trading happened. 4.5 is how I use the POC as an entry or an exit. And 4.6 puts all of it together with your CRT setup." },

    // 4.1
    { kind: "divider", lesson: "4.1", say: "Lesson 4.1. What session liquidity means." },
    { kind: "cards", lesson: "4.1", label: "TELL", title: "Three Sessions, Three Ranges",
      cards: [
        { head: "ASIA", big: "7:00 PM\nto 2:59 AM", body: "Eastern time" },
        { head: "LONDON", big: "3:00 AM\nto 9:29 AM", body: "Eastern time" },
        { head: "NEW YORK", big: "9:30 AM\nto 3:59 PM", body: "Eastern time" },
      ],
      note: "Each session leaves a high and a low on your chart.",
      say: "Every trading session has its own high and its own low. Asia runs 7 PM to 2:59 AM Eastern. London runs 3 AM to 9:29. New York runs 9:30 AM to 3:59 PM. Three sessions, so six levels on your chart every day." },
    { kind: "statement", lesson: "4.1", label: "TELL", title: "Sand at the Base of a Slide",
      big: "Stops and pending orders pile up at session highs and lows.",
      sub: "That pile of orders is fuel. I treat those levels as targets.",
      say: "Here's why those levels matter. Stop-losses and pending orders cluster around them, like sand piling up at the base of a slide. That pile of orders is fuel. So I treat those highs and lows as targets. When price runs toward one, it's going where the orders are." },
    { kind: "live", lesson: "4.1", title: "Session Lines on a Live Chart",
      cues: ["Turn on the Session Liquidity indicator", "Point to each session's high and low", "Show what price does with London's high once New York opens"],
      demo: 2,
      say: "Let me show you on a live chart. [Switch to TradingView.] This is the Session Liquidity indicator. This line is the Asia high, and this one is the Asia low. Here's London's high and low. Now New York opens at 9:30. Watch London's high. [Scroll forward.] See how price went after it? That's the liquidity resting there, and that's why I mark these lines every morning. [Switch back to the slides.]" },
    { kind: "do", lesson: "4.1",
      steps: ["Turn on your Session Liquidity indicator", "Screenshot your chart with all three sessions' lines visible", "Post it in the community"],
      say: "Your turn. Turn on your Session Liquidity indicator if you haven't yet. Screenshot your chart with all three sessions' lines showing. Post it." },

    // 4.2
    { kind: "divider", lesson: "4.2", say: "Lesson 4.2. Reading the three sessions." },
    { kind: "flow", lesson: "4.2", label: "TELL", title: "Sessions Hand Off to Each Other",
      boxes: [
        { head: "ASIA", body: "Builds a range" },
        { head: "LONDON", body: "Often sweeps the Asia range" },
        { head: "NEW YORK", body: "Often goes after the level nobody touched yet" },
      ],
      note: "Same lines as 4.1. Now we read how they interact.",
      say: "Same tool, more depth. In 4.1 you spotted the lines. Now we read how the sessions interact. Asia builds a range. London often sweeps that range. Then New York often goes after whichever session level hasn't been touched yet. Often, not always. That's why we watch it every day." },
    { kind: "live", lesson: "4.2", title: "One Full Day, Session by Session",
      cues: ["Start at the Asia open and mark its range", "Show London sweeping the Asia high or low", "Show New York going after the untouched level"],
      demo: 3,
      say: "Let's walk one full day. [Switch to TradingView.] Here's the Asia open. Price builds this range overnight. Here's the high, here's the low. Now London opens at 3 AM. Watch what it does to the Asia range. [Scroll.] There's the sweep. Now which level is still sitting there untouched? This one. New York opens at 9:30, and here's price going after it. [Switch back.]" },
    { kind: "do", lesson: "4.2",
      steps: ["Track today's three session highs and lows on your chart", "At the end of the day, post which one got swept first"],
      say: "Your turn. Track today's three session highs and lows on your chart. At the end of the day, post which one got swept first." },

    // 4.3
    { kind: "divider", lesson: "4.3", say: "Lesson 4.3. Fixed Range Volume Profile basics." },
    { kind: "statement", lesson: "4.3", label: "TELL", title: "A Different Question",
      big: "Not \"where did price go?\"\nBut \"where did the most trading happen?\"",
      sub: "That's what volume profile answers.",
      say: "This tool answers a different question than price alone. Not where did price go. Where did the most trading happen. Price tells you the path. Volume profile tells you where buyers and sellers spent the most time agreeing." },
    { kind: "cards", lesson: "4.3", label: "TELL", title: "Two Words to Know",
      cards: [
        { head: "POC", color: "accent", body: "Point of Control. The single price with the most volume." },
        { head: "VALUE AREA", color: "blue", body: "The zone holding about 70% of the volume. That's TradingView's default." },
      ],
      note: "I draw it on the 30-minute chart.",
      say: "Two words to know. POC, the Point of Control, is the single price with the most volume. The value area is the zone around it holding about 70% of the volume. That's TradingView's default setting, so leave it there. And I draw this on the 30-minute chart. That's the timeframe for everything in this module." },
    { kind: "image", lesson: "4.3", label: "EXAMPLE", title: "What the Profile Looks Like", img: "ex_profile.png", ar: 2.7000,
      caption: "Example with synthetic candles, not a real trade",
      say: "Here's what it looks like. The bars on the right are volume at each price. The longest bar is the POC, in orange. The purple band marks the value area. On a normal session you get a fat middle and thin edges." },
    { kind: "live", lesson: "4.3", title: "Fixed Range Volume Profile, Live",
      cues: ["30-minute chart", "Draw Fixed Range Volume Profile over a recent session", "Point out the POC and the value area"],
      demo: 2,
      say: "Now on a live chart. [Switch to TradingView.] I'm on the 30-minute chart. I pick the Fixed Range Volume Profile tool, click the start of the session, and drag to the end. Here's the POC, the price with the most volume. Here's the value area. Fat middle, thin edges. That's a normal session. [Switch back.]" },
    { kind: "do", lesson: "4.3",
      steps: ["Draw Volume Profile on yesterday's session, 30-minute chart", "Screenshot it and mark where the POC landed"],
      say: "Your turn. Apply Volume Profile to yesterday's session on your own 30-minute chart. Screenshot it and mark where the POC landed." },

    // 4.4
    { kind: "divider", lesson: "4.4", say: "Lesson 4.4. Using volume to confirm zones." },
    { kind: "cards", lesson: "4.4", label: "TELL", title: "High Volume vs. Low Volume",
      cards: [
        { head: "HIGH-VOLUME NODE", color: "blue", body: "Price agrees it belongs here. It may pause or reverse. Harder for a sweep to punch through cleanly." },
        { head: "LOW-VOLUME GAP", color: "accent", body: "Price moved through fast. Less in the way. This is where I often see manipulation sweeps." },
      ],
      say: "High-volume areas mean price agrees it belongs there. It might pause there or reverse, and it's harder for a sweep to punch through cleanly. Low-volume gaps mean price moved through fast, without much disagreement. That's where I often see manipulation sweeps happen, because there's less resistance." },
    { kind: "image", lesson: "4.4", label: "EXAMPLE", title: "Volume Confirms the Sweep", img: "ex_gap_node.png", ar: 2.6154,
      caption: "Example with synthetic candles on a 30-minute chart, not a real trade",
      say: "Here's the picture. On the left, the sweep goes through a low-volume gap. One wick through, then price reverses hard. Clean. On the right, the sweep goes into a high-volume node. Price chops around inside it, and the reversal is hard to read. Same sweep, different volume, different trade." },
    { kind: "live", lesson: "4.4", title: "Gap vs. Node on Real Sweeps",
      cues: ["Sweep #1: through a low-volume gap (fast, clean)", "Sweep #2: into a high-volume node (choppy)", "Compare how each reversal looked"],
      demo: 3,
      say: "Let's look at two real sweeps. [Switch to TradingView.] Sweep one. Profile's drawn on the 30-minute chart. Look where the wick went: through this thin area, a low-volume gap. One push through and price snapped back. Now sweep two. This one ran into a high-volume node. Look at the chop. Three, four candles going nowhere before anything happened. That's the difference. [Switch back.]" },
    { kind: "do", lesson: "4.4",
      steps: ["Pull up your Module 3 CRT screenshot", "Overlay Volume Profile on it, 30-minute chart", "Post: did the sweep pass through high or low volume?"],
      say: "Your turn. Pull up your Module 3 CRT screenshot again. Overlay Volume Profile on it, drawn on the 30-minute chart. Post whether the sweep passed through high or low volume, and whether that changes how you'd read the setup." },

    // 4.5
    { kind: "divider", lesson: "4.5", say: "Lesson 4.5. Using the POC as an entry or an exit." },
    { kind: "statement", lesson: "4.5", label: "TELL", title: "One Line, Two Jobs",
      big: "I use the POC as my exit\nor as my entry.",
      sub: "This is how I trade it. It's not a law the market has to follow.",
      say: "In 4.4 we used volume to judge the sweep. Now I'm going to show you how I use one line off that profile, the POC, as my exit or my entry. This is how I trade it. It's not a law the market has to follow." },
    { kind: "steps", lesson: "4.5", label: "TELL", title: "The POC as My Exit",
      steps: ["Draw the profile on the 30-minute chart, over the range I'm trading", "After the sweep and my CRT entry, I manage the trade at the POC, or a few ticks before it", "Full exit or a partial with a runner: I decide from how the candles move into the POC"],
      say: "First, the POC as my exit. I draw the Fixed Range Volume Profile on the 30-minute chart, over the range I'm trading. After the sweep and my CRT entry, I manage the trade at the POC of that range, or a few ticks before it. Sometimes I take the full exit there. Sometimes I take a partial and let the rest run. Which one depends on how the candles move into the POC. That's a read, not a formula. You build the feel for it with screen time." },
    { kind: "image", lesson: "4.5", label: "EXAMPLE", title: "The POC as the Exit", img: "ex_poc_exit.png", ar: 2.3599,
      caption: "Example with synthetic candles on a 30-minute chart, not a real trade",
      say: "Here's the exit on a chart. The gray box is the range I profiled. Price sweeps under the range low, then reverses. Entry on the reversal, hard stop 3.5 to 4 points below it. And the target is the POC of that range, the orange line. That's where I expect price to slow down." },
    { kind: "compare", lesson: "4.5", label: "TELL", title: "Where It's Headed vs. Where It Slows Down",
      left: { head: "SESSION LIQUIDITY", body: "Where price is headed" },
      right: { head: "POC", body: "Where price is likely to slow down on the way" },
      say: "Why the POC? It's where the most trading happened in that range, so that's where I expect price to stall. Session liquidity tells me where price is headed. The POC tells me where it's likely to slow down on the way." },
    { kind: "steps", lesson: "4.5", label: "TELL", title: "The POC as My Entry",
      steps: ["Price leaves the range, then comes back to the POC", "I don't enter on the touch. I wait for a reaction candle at the POC", "If it lines up with my CRT direction, I enter on that candle's close"],
      say: "Second, the POC as my entry. When price leaves the range and comes back to the POC, I watch how it reacts there. I don't enter on the touch. I wait for a reaction candle at the POC. If it lines up with my CRT direction, I enter on that candle's close." },
    { kind: "stats", lesson: "4.5", label: "TELL", title: "Your Stop and Target on a POC Entry",
      stats: [
        { num: "3.5–4", label: "point hard stop, measured from the reaction candle's close" },
        { num: "Session H/L", label: "target: the untaken liquidity in your direction" },
        { num: "±1 pt", label: "exit at that line or within a point of it" },
      ],
      note: "No stop, no trade. Full risk rules are in Module 5.",
      say: "Now your stop. I manage my own trades by hand, but that's me, not you. You use a hard stop of 3.5 to 4 points on ES. On a POC entry, that's 3.5 to 4 points from your entry, the close of the reaction candle. If you're a beginner, you don't take a trade without a stop. No exceptions. My target is the session high or the session low, whichever is the untaken liquidity in my trade direction. I exit at that line or within a point of it. We cover size and risk in detail in Module 5." },
    { kind: "image", lesson: "4.5", label: "EXAMPLE", title: "The POC as the Entry", img: "ex_poc_entry.png", ar: 2.2796,
      caption: "Example with synthetic candles on a 30-minute chart, not a real trade",
      say: "And here's the entry. Price leaves the range, then comes back to the POC. I don't enter on the touch. This candle wicks into the POC and closes back up. That's the reaction candle. Entry on its close. Hard stop 3.5 to 4 points below the entry. Target is the session high nobody's taken yet, up here." },
    { kind: "live", lesson: "4.5", title: "The POC on Real Setups",
      cues: ["30-minute chart: draw the profile over the range you trade", "Setup #1: the POC as the target", "Setup #2: the POC as the entry, with stop and target marked"],
      demo: 4,
      say: "Now on real charts. [Switch to TradingView.] 30-minute chart. I draw the profile over the range I'm trading, start to end. Here's the POC. Setup one: here's the sweep, here's my CRT entry, and the POC is my target. Look at how the candles slowed down coming into it. Setup two: price left the range, came back down to the POC, and printed this reaction candle. Entry on its close. Hard stop 3.5 to 4 points below. Target up here at the session high nobody's taken yet. [Switch back.]" },
    { kind: "do", lesson: "4.5",
      steps: ["On the 30-minute chart, draw Volume Profile on your range and mark the POC", "On your Module 3 CRT screenshot, mark the POC: entry or target?", "Post it with your entry, stop and target marked"],
      say: "Your turn. On the 30-minute chart, draw Volume Profile on the range you're trading and mark the POC. Then pull up your Module 3 CRT screenshot and mark the POC on it. Was it your entry or your target? Post it with your entry, stop and target marked. One line doesn't make the trade. The POC has to fit the setup." },

    // 4.6
    { kind: "divider", lesson: "4.6", say: "Lesson 4.6. Combining both tools with CRT." },
    { kind: "flow", lesson: "4.6", label: "TELL", title: "3 Tools, 1 Trade",
      boxes: [
        { head: "SESSION LIQUIDITY", body: "Where price is headed" },
        { head: "CRT", body: "The sweep and the entry" },
        { head: "VOLUME PROFILE", body: "Does volume agree? Where's the POC?" },
      ],
      note: "None of these tools work alone. They have to agree.",
      say: "None of these tools work in isolation. Session liquidity tells you where price is headed. CRT gives you the sweep and the entry. Volume profile tells you if volume agrees, and where the POC sits. When all three agree, that's the trade. This lesson proves it out loud, one more time, on a live example." },
    { kind: "live", lesson: "4.6", title: "One Trade, All Three Tools",
      cues: ["Mark the session liquidity target", "Show the CRT sweep into it", "Volume profile (30m): sweep through a low-volume gap, entry, POC as the target"],
      demo: 4,
      say: "[Switch to TradingView.] Step one, session liquidity. Which level is untaken? This one. That's where price is headed. Step two, CRT. Here's the sweep, right into that level. Step three, volume. Profile's on the 30-minute chart, and look: the sweep went through a low-volume gap. Clean. Here's the entry, and the POC is my target. Three tools, all saying the same thing. [Switch back.]" },
    { kind: "do", lesson: "4.6",
      steps: ["Find your own three-tool example this week", "Session liquidity + CRT + Volume Profile all agreeing, POC marked as your target", "Post it whenever you spot one. No deadline."],
      say: "Your turn. Find your own three-tool confluence example this week. Session liquidity, CRT and Volume Profile all agreeing, with the POC marked as your target. Post it whenever you spot one. No deadline." },
    { kind: "recap", lesson: "outro", title: "Module 4 in One Slide",
      items: ["Session highs and lows are where the orders sit", "London often sweeps Asia. New York often hunts the untouched level", "POC = most-traded price. Draw it on the 30-minute chart", "Sweeps through low-volume gaps read cleaner", "The POC is your exit or your entry. Hard stop 3.5–4 points, every time"],
      next: "Next: Module 5, Full Workflow & Risk Management",
      say: "That's Module 4. Session highs and lows are where the orders sit. London often sweeps Asia, and New York often goes after the level nobody touched. The POC is the most-traded price, drawn on the 30-minute chart. Sweeps through low-volume gaps read cleaner. And the POC is your exit or your entry, with a 3.5 to 4 point hard stop every time. Next up, Module 5: putting it into one workflow, and the risk rules that keep you in the game." },
  ],
};

const M5 = {
  file: "module_5_workflow_risk_v4.pptx",
  module: "MODULE 5",
  name: "Full Workflow & Risk Management",
  lessons: {
    "5.1": "Pre-Trade Checklist",
    "5.2": "Position Sizing & Daily Risk Rules",
    "5.3": "Stop Placement",
    "5.4": "Full Worked Example",
  },
  slides: [
    { kind: "title", lesson: "intro", module: "MODULE 5", title: "Full Workflow &\nRisk Management", sub: "One repeatable process, and the risk math that keeps it survivable",
      say: "Welcome to Module 5. You've got every tool now. This module turns them into one process you run the same way every time, and gives you the risk rules that keep you trading next month." },
    { ...DISCLAIMER, lesson: "intro",
      say: "Same note as last module. This is education, not financial advice. Futures carry a real risk of loss. The dollar numbers in this module are examples of risk, not promises of profit. Only trade money you can afford to lose." },
    { kind: "agenda", lesson: "intro", title: "Module 5 Lessons",
      say: "Four lessons. 5.1 is the checklist you run before every trade. 5.2 is position size and your daily limits. 5.3 is where your stop goes. And 5.4 is one full trade, start to finish." },

    // 5.1
    { kind: "divider", lesson: "5.1", say: "Lesson 5.1. The pre-trade checklist." },
    { kind: "checklist", lesson: "5.1", label: "TELL", title: "Glue This to Your Monitor",
      steps: ["Confirm the AMD phase", "Check the daily bias (higher timeframe)", "In your window: 10 AM–12 PM ET while learning", "Identify the session liquidity targets", "Volume profile agrees (30m). POC: entry or target?", "Confirm CRT confluence", "Define your risk before entry"],
      say: "This is the one thing I want glued to your monitor. Seven steps before any entry. One, confirm the AMD phase. Two, check the higher-timeframe daily bias. Three, confirm you're in your window. While you're learning, that's 10 AM to 12 PM Eastern. Four, identify the session liquidity targets. Five, check that volume profile agrees on the 30-minute chart, and mark the POC. Is it your entry or your target? Six, confirm CRT confluence. Seven, define your risk before entry." },
    { kind: "statement", lesson: "5.1", label: "TELL", title: "Every Single Time",
      big: "No skipping steps because you're excited.",
      sub: "The checklist is what keeps a good setup from turning into a guess.",
      say: "Every single time. No skipping steps because you're excited. The day you skip one is the day you take the trade you shouldn't have." },
    { kind: "live", lesson: "5.1", title: "The Checklist on a Real Setup",
      cues: ["Pick a recent setup", "Run all 7 steps out loud", "Check off each one as you go"],
      demo: 3,
      say: "Let's run it on a real setup. [Switch to TradingView.] Step one, AMD phase: [say the phase]. Step two, daily bias: [say it]. Step three, the time is [say it], inside the window. Step four, session liquidity: the untaken level is here. Step five, volume profile on the 30-minute: here's the POC, and it's my [entry or target]. Step six, CRT: here's the sweep and the confirmation. Step seven, risk: hard stop 3.5 to 4 points, here. Seven for seven. That's a trade I'm allowed to take. [Switch back.]" },
    { kind: "do", lesson: "5.1",
      steps: ["Print or save this checklist where you'll see it before every trade", "Post a photo of where you put it: screen, wall, notebook"],
      say: "Your turn. Print or save this checklist somewhere you'll see it before every trade. Post a photo of wherever you put it. Screen, wall, notebook, doesn't matter." },

    // 5.2
    { kind: "divider", lesson: "5.2", say: "Lesson 5.2. Position sizing and daily risk rules." },
    { kind: "equation", lesson: "5.2", label: "TELL", title: "The Sizing Formula",
      parts: ["$ you'll risk", "stop in points", "$50 per point"],
      result: "contracts",
      example: "Example: $200 ÷ 4 points ÷ $50 = 1 ES contract",
      say: "Here's the math in plain terms. Decide how many dollars you're willing to risk on this one trade. Divide that by how many points your stop is from entry. Divide by 50 dollars, the ES point value. That's your number of contracts. So 200 dollars, divided by a 4 point stop, divided by 50, is 1 contract. That's the formula professional position sizing is built on." },
    { kind: "options", lesson: "5.2", label: "TELL", title: "Your Size While You Learn: Pick One",
      a: { head: "OPTION A", big: "1 ES", lines: ["$50 per point", "A stopped trade: $175–200", "Daily limit: $200"] },
      b: { head: "OPTION B", big: "2 ES", lines: ["$100 per point", "A stopped trade: $350–400", "Daily limit: $400. One loss ends your session"] },
      note: "A: smaller hit per loss. B: bigger moves, bigger losses.",
      say: "But that's not what you'll use day to day while you're in this program. I'm giving you two options instead. Option A, 1 ES contract. Every point is 50 dollars. With the 3.5 to 4 point hard stop, one stopped trade is 175 to 200 dollars, inside a 200 dollar limit. Option B, 2 ES contracts. Every point is 100 dollars, and your daily limit goes up to 400. One stopped trade is 350 to 400 dollars, so that one loss ends your session. Here's the trade-off. A takes a smaller hit per loss. B makes bigger moves, and takes bigger losses. It's your choice." },
    { kind: "stats", lesson: "5.2", label: "TELL", title: "Keep It Fixed",
      stats: [
        { num: "1 or 2", label: "ES contracts, your choice, the same on every trade" },
        { num: "1.5x–2x", label: "account growth before you size up" },
        { num: "4", label: "ES contracts max once you hit that milestone" },
      ],
      say: "Whichever you pick, keep it fixed, every trade. Stay with it until your account has grown 1.5 to 2 times your starting capital. Once you hit that milestone, you can size up, to a max of 4 contracts." },
    { kind: "statement", lesson: "5.2", label: "TELL", title: "Know Your Number Before You Trade",
      big: "How many losing trades until you hit your daily limit?",
      sub: "If you can't answer that before the open, you're flying blind.",
      say: "Know your number before you trade. On Option A, your hard stop risks 175 to 200 dollars per trade. On Option B, it's 350 to 400, and one loss ends your session. So do the quick math for your option. How many losing trades would it take to hit your daily limit? If you don't know that number before you start trading, you're flying blind. Once you can answer it without doing math in the moment, you're ready to size up, to a max of 4." },
    { kind: "stats", lesson: "5.2", label: "TELL", title: "My Numbers, Not Yours",
      stats: [
        { num: "$1,000", label: "max risk, total, per day" },
        { num: "$200", label: "max during the manipulation session, 3:00–9:29 AM" },
        { num: "1–2", label: "good trades, then I'm done" },
      ],
      note: "Set your own cap. In an eval, use the firm's daily loss limit.",
      say: "Here are my numbers. I never risk more than 1,000 dollars total in a single day, and no more than 200 of that during the manipulation session, 3 to 9:29 AM, which I don't want you trading yet anyway. My daily goal is 1 or 2 good trades, then I'm done. These are my numbers, not yours. Set your own daily cap before you trade. In an eval, it's the firm's daily loss limit. And more trades isn't better. It usually means you stopped waiting for the real setup." },
    { kind: "cards", lesson: "5.2", label: "TELL", title: "Your Daily Profit Goal (While Learning)",
      cards: [
        { head: "FLAT", big: "$400 / day", body: "Simple. Same number every day." },
        { head: "PERSONALIZED", big: "Hourly × 8 × 2", body: "Example: $20 × 8 = $160, × 2 = $320" },
      ],
      note: "A reference number, not a quota. Stop after 1–2 good trades.",
      say: "While you're learning, set a daily profit goal. Two ways. A flat 400 dollars a day. Or personalize it. Take your hourly rate, multiply by 8, then multiply that by 2. So at 20 dollars an hour, 20 times 8 is 160, times 2 is 320. It's a reference number, not a quota. You still stop after 1 or 2 good trades." },
    { kind: "live", lesson: "5.2", title: "Sizing a Real Setup",
      cues: ["Measure a 3.5–4 point hard stop on a real setup", "Option A, 1 ES: $175–200 of risk", "Option B, 2 ES: $350–400. One loss ends the session"],
      demo: 2,
      say: "[Switch to TradingView.] Here's a real setup. Entry here. Hard stop 3.5 to 4 points away, here. On Option A, 1 ES contract, that's 175 to 200 dollars of risk on this trade. On Option B, 2 ES contracts, it's 350 to 400, and if it stops out, my session's over. And here's my profit goal for the day next to it, so I know what done looks like. [Switch back.]" },
    { kind: "do", lesson: "5.2",
      steps: ["Pick Option A (1 ES) or B (2 ES). Your dollar risk on a real setup with the hard stop", "Your daily limit, and how many losers like that it allows", "Your daily profit goal: $400 flat, or hourly × 8 × 2. Post all three"],
      say: "Your turn. Three numbers, posted together. One: pick Option A or Option B, then use the 3.5 to 4 point hard stop on a real setup from your chart, and write your dollar risk on that trade. Two: write down your daily limit, then how many losers like that one it allows. Three: your daily profit goal, either 400 flat or your hourly rate times 8 times 2." },

    // 5.3
    { kind: "divider", lesson: "5.3", say: "Lesson 5.3. Stop placement." },
    { kind: "bigstat", lesson: "5.3", label: "TELL", title: "A Hard Stop, Every Setup",
      num: "3.5–4 pts", label2: "from your entry on ES",
      sub: "The sweep entry and the POC entry. Every trade. No exceptions.",
      say: "Your stop is a hard stop, 3.5 to 4 points from your entry on ES. Every setup: the sweep entry and the POC entry. No exceptions." },
    { kind: "table", lesson: "5.3", label: "TELL", title: "What That Stop Costs",
      rows: [["", "Per point", "One stopped trade"], ["Option A: 1 ES", "$50", "$175–200"], ["Option B: 2 ES", "$100", "$350–400"]],
      note: "Before commissions. Know this number before you click.",
      say: "Here's what that costs. On Option A, 1 contract, 175 to 200 dollars. On Option B, 2 contracts, 350 to 400 dollars. Plus commissions. Know this number before you click." },
    { kind: "statement", lesson: "5.3", label: "TELL", title: "If Price Gets There, You're Out",
      big: "Your stop is where your read was wrong.",
      sub: "I manage my own trades by hand. That's me, not you. You use the hard stop.",
      say: "I manage my own trades by hand, but that's me, not you. You use the hard stop, and you never take a trade without one. If price gets there, your read on the setup was wrong, and you're out. No moving it. No hoping." },
    { kind: "live", lesson: "5.3", title: "Measuring the Hard Stop",
      cues: ["Take a sweep entry", "Measure 3.5–4 points from the entry and count it out loud", "Show the dollar risk for Option A and Option B"],
      demo: 2,
      say: "[Switch to TradingView.] Here's a sweep entry. I'll use the measure tool from the entry and count the points: 1, 2, 3, 3 and a half, 4. That's 14 to 16 ticks. Stop goes here. On 1 contract that's 175 to 200 dollars. On 2 contracts, 350 to 400. [If the indicator draws its own stop line at the sweep wick, point out that it's a different line: in this course you measure 3.5 to 4 points from your entry.] [Switch back.]" },
    { kind: "do", lesson: "5.3",
      steps: ["On your Module 3 CRT screenshot, mark your entry and a 3.5–4 point hard stop", "Post it with your dollar risk for your option, 1 or 2 ES"],
      say: "Your turn. On your CRT screenshot from Module 3, mark your entry and a 3.5 to 4 point hard stop from it. Post it with your dollar risk for your option, 1 or 2 ES contracts." },

    // 5.4
    { kind: "divider", lesson: "5.4", say: "Lesson 5.4. The full worked example." },
    { kind: "flowsteps", lesson: "5.4", label: "TELL", title: "One Trade. Every Piece.",
      steps: ["AMD read", "CRT entry", "Liquidity and volume agree", "Position size", "Hard stop, 3.5–4 pts", "Target, in R"],
      say: "One real trade, every piece of this curriculum, start to finish. The AMD read. The CRT entry. Session liquidity and volume confirmation. Position size. A 3.5 to 4 point hard stop. And the target. This is the lesson that proves it's one process, not five separate tools you're juggling." },
    { kind: "ladder", lesson: "5.4", label: "TELL", title: "Measure the Target in R",
      rungs: [{ r: "2R", pts: "7–8 pts" }, { r: "1R", pts: "3.5–4 pts" }, { r: "Entry", pts: "" }, { r: "Stop", pts: "3.5–4 pts below entry" }],
      text: "Your target is the top or bottom of the range. Measure it against your stop.",
      say: "The target is the top or the bottom of the range. Measure it in R against your stop. 1R is your stop distance, 3.5 to 4 points. So 2R is 7 to 8 points." },
    { kind: "live", lesson: "5.4", title: "One Trade, Start to Finish",
      cues: ["AMD read, daily bias, time window", "Session liquidity + CRT entry + volume profile", "Position size, 3.5–4 pt hard stop, target measured in R"],
      demo: 6,
      say: "[Switch to TradingView.] One trade, start to finish. First the AMD read: [say the phase]. Daily bias: [say it]. Time: inside the 10 to 12 window. Session liquidity: the untaken level is here. That's where price is headed. Volume profile on the 30-minute: here's the POC. CRT: here's the sweep, and here's my entry. Size: [Option A or B], so my risk is [dollar amount]. Hard stop, 3.5 to 4 points, here. Target, the top of the range, here. That's [number] points, so about [number] R. Here's what price did. [Walk it forward to the exit, win or loss.] [Switch back.]" },
    { kind: "do", lesson: "5.4",
      steps: ["Re-create this walkthrough on your own chart with a setup from this week", "Post the full breakdown, every step"],
      note: "This is your Module 5 capstone.",
      say: "Your turn, and this is your Module 5 capstone. Re-create this exact walkthrough on your own chart, using a setup from this week. Post the full breakdown, every step." },
    { kind: "recap", lesson: "outro", title: "Module 5 in One Slide",
      items: ["Run the 7-step checklist before every trade", "1 or 2 ES, fixed, until your account grows 1.5x–2x", "Know how many losers your daily limit allows", "Hard stop 3.5–4 points from entry, every setup", "Measure every target in R"],
      next: "One process. Not five separate tools.",
      say: "That's Module 5. Run the checklist before every trade. 1 or 2 contracts, fixed, until your account grows 1.5 to 2 times. Know how many losers your daily limit allows. Hard stop, 3.5 to 4 points, every setup. And measure every target in R. One process, not five separate tools. Post your capstone, and I'll see you in the community." },
  ],
};

module.exports = { M4, M5 };
